_format_version: '3.0'
services:
  - name: auth-service
    url: http://host.docker.internal:8080
    routes:
      - name: auth-route
        paths:
          - /auth
plugins:
  - name: cors
    config:
      origins:
        - http://localhost:3090
      methods: [GET, POST, PUT, DELETE, OPTIONS]
      headers: [Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, Authorization]
      exposed_headers: [X-Auth-Token]
      credentials: true
      max_age: 3600
